from breezy.tree import Tree

def sanitize_session_name(name: str) -> str: ...
def generate_session_id(name: str) -> str: ...
def export_vcs_tree(tree: Tree, path: str, subpath: str | None = None) -> None: ...
